import os
import json
import uuid
from typing import Dict, Any, List
import google.generativeai as genai

class RecipeGenerator:
    def __init__(self):
        genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
        self.model = genai.GenerativeModel('gemini-1.5-flash')

    async def generate_adaptive_recipe(
        self, 
        ingredients: List[str], 
        diet_type: str = "", 
        allergies: str = "",
        user_message: str = ""
    ) -> Dict[str, Any]:
        """
        Generates a custom recipe from the ingredients, dietary preferences, and user comments.
        Returns a structured dictionary mapping to Recipe model.
        """
        ingredients_str = ", ".join(ingredients)
        
        prompt = f"""
        You are Vinsmoke Sanji, the master chef. Your mission is to write a gorgeous, professional recipe.
        
        INPUT DETAILS:
        - Base ingredients available: {ingredients_str}
        - Diet Type restriction: {diet_type}
        - Allergies/Restrictions to avoid: {allergies}
        - User request context: {user_message}

        Generate a high-quality recipe that is appropriate for these constraints.
        Provide the response strictly formatted as a JSON object:
        {{
          "title": "A beautiful One Piece / Baratie inspired recipe title",
          "description": "A mouth-watering description of the dish",
          "ingredients": ["Detail quantity and ingredient name 1", "Detail quantity and ingredient name 2"],
          "instructions": ["Step 1 explanation", "Step 2 explanation"],
          "prepTime": "XX mins",
          "category": "One of: Appetizer, Seafood, Noodles, Dessert, Main Course",
          "tags": ["Tag1", "Tag2"],
          "chefTips": ["Practical, professional tip from Sanji about cooking this dish"]
        }}
        Do not include markdown code block tags like ```json. Return only the raw JSON string.
        """

        try:
            if not os.getenv("GEMINI_API_KEY"):
                raise ValueError("GEMINI_API_KEY is not configured")
            response = self.model.generate_content(prompt)
            content = response.text.strip()
            
            if "```json" in content:
                content = content.split("```json")[1].split("```")[0].strip()
            elif "```" in content:
                content = content.split("```")[1].split("```")[0].strip()

            data = json.loads(content)
            
            # Populate default and generated fields
            recipe_id = f"custom_{uuid.uuid4().hex[:8]}"
            return {
                "id": recipe_id,
                "title": data.get("title", "Baratie Special Creation"),
                "description": data.get("description", "A custom recipe generated by your AI Chef Companion."),
                "ingredients": data.get("ingredients", ingredients),
                "instructions": data.get("instructions", ["Cook everything together beautifully!"]),
                "imageUrl": "https://example.com/custom_recipe.jpg",
                "prepTime": data.get("prepTime", "30 mins"),
                "category": data.get("category", "Main Course"),
                "tags": data.get("tags", ["Custom"]),
                "chefTips": data.get("chefTips", ["Cook with passion!"]),
                "isFavorite": False,
                "isCustom": True
            }
        except Exception as e:
            print(f"Error in RecipeGenerator: {e}")
            return {
                "id": f"custom_{uuid.uuid4().hex[:8]}",
                "title": "East Blue Stir Fry",
                "description": "A quick, nourishing meal prepared with available ingredients.",
                "ingredients": [f"1 cup of {ing}" for ing in ingredients] if ingredients else ["Rice", "Oil", "Salt"],
                "instructions": ["Heat pan with oil.", "Stir fry ingredients until cooked through.", "Season and serve hot."],
                "imageUrl": "https://example.com/custom_recipe.jpg",
                "prepTime": "15 mins",
                "category": "Main Course",
                "tags": ["Quick", "Stir-Fry"],
                "chefTips": ["Keep the pan hot and don't stop moving the ingredients!"],
                "isFavorite": False,
                "isCustom": True
            }
        
